# Generated by Django 3.1 on 2023-03-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_AddStocksAndTradeModel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('quote', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Qoutes',
            },
        ),
    ]
